# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_input_data_form.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 602)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(650, 600))
        Dialog.setMaximumSize(QtCore.QSize(650, 602))
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(15, 11, 620, 580))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(620, 580))
        self.tabWidget.setMaximumSize(QtCore.QSize(620, 580))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(600, 521))
        self.scrollArea.setMaximumSize(QtCore.QSize(554, 521))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 598, 519))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.DissolvedOxygen_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.DissolvedOxygen_checkBox.setText("")
        self.DissolvedOxygen_checkBox.setObjectName("DissolvedOxygen_checkBox")
        self.gridLayout.addWidget(self.DissolvedOxygen_checkBox, 0, 5, 1, 1)
        self.NitrousAcidNitrogen_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.NitrousAcidNitrogen_checkBox.setText("")
        self.NitrousAcidNitrogen_checkBox.setObjectName("NitrousAcidNitrogen_checkBox")
        self.gridLayout.addWidget(self.NitrousAcidNitrogen_checkBox, 0, 9, 1, 1)
        self.SilicicAcidSilicon_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.SilicicAcidSilicon_checkBox.setText("")
        self.SilicicAcidSilicon_checkBox.setObjectName("SilicicAcidSilicon_checkBox")
        self.gridLayout.addWidget(self.SilicicAcidSilicon_checkBox, 0, 13, 1, 1)
        self.NitricAcidNitrogen_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.NitricAcidNitrogen_checkBox.setText("")
        self.NitricAcidNitrogen_checkBox.setObjectName("NitricAcidNitrogen_checkBox")
        self.gridLayout.addWidget(self.NitricAcidNitrogen_checkBox, 0, 11, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.PhosphatePhosphorus_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.PhosphatePhosphorus_checkBox.setText("")
        self.PhosphatePhosphorus_checkBox.setObjectName("PhosphatePhosphorus_checkBox")
        self.gridLayout.addWidget(self.PhosphatePhosphorus_checkBox, 0, 7, 1, 1)
        self.WaterTemp_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.WaterTemp_checkBox.setText("")
        self.WaterTemp_checkBox.setObjectName("WaterTemp_checkBox")
        self.gridLayout.addWidget(self.WaterTemp_checkBox, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 6, 1, 1)
        self.Salinity_checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.Salinity_checkBox.setText("")
        self.Salinity_checkBox.setObjectName("Salinity_checkBox")
        self.gridLayout.addWidget(self.Salinity_checkBox, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 10, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 12, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 8, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 3)
        self.All_Data_read_csv_Pushbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.All_Data_read_csv_Pushbutton.setMinimumSize(QtCore.QSize(0, 40))
        self.All_Data_read_csv_Pushbutton.setObjectName("All_Data_read_csv_Pushbutton")
        self.gridLayout_2.addWidget(self.All_Data_read_csv_Pushbutton, 0, 1, 2, 1)
        self.All_Data_read_csv_TextEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.All_Data_read_csv_TextEdit.setEnabled(True)
        self.All_Data_read_csv_TextEdit.setObjectName("All_Data_read_csv_TextEdit")
        self.gridLayout_2.addWidget(self.All_Data_read_csv_TextEdit, 3, 0, 1, 3)
        self.LoadFile_PushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.LoadFile_PushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.LoadFile_PushButton.setObjectName("LoadFile_PushButton")
        self.gridLayout_2.addWidget(self.LoadFile_PushButton, 0, 2, 2, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.All_Data_read_csv_lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.All_Data_read_csv_lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.All_Data_read_csv_lineEdit.setObjectName("All_Data_read_csv_lineEdit")
        self.gridLayout_2.addWidget(self.All_Data_read_csv_lineEdit, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_10.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_5.sizePolicy().hasHeightForWidth())
        self.scrollArea_5.setSizePolicy(sizePolicy)
        self.scrollArea_5.setMinimumSize(QtCore.QSize(600, 521))
        self.scrollArea_5.setMaximumSize(QtCore.QSize(554, 521))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 598, 519))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.scrollAreaWidgetContents_5)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout.addWidget(self.calendarWidget)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_11.addWidget(self.label_27)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Area_EestSea_Cbox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.Area_EestSea_Cbox_2.setObjectName("Area_EestSea_Cbox_2")
        self.verticalLayout.addWidget(self.Area_EestSea_Cbox_2)
        self.Area_WestSea_Cbox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.Area_WestSea_Cbox_2.setObjectName("Area_WestSea_Cbox_2")
        self.verticalLayout.addWidget(self.Area_WestSea_Cbox_2)
        self.Area_SouthSea_Cbox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.Area_SouthSea_Cbox_2.setObjectName("Area_SouthSea_Cbox_2")
        self.verticalLayout.addWidget(self.Area_SouthSea_Cbox_2)
        self.Area_EastChinaSea_Cbox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_5)
        self.Area_EastChinaSea_Cbox_2.setObjectName("Area_EastChinaSea_Cbox_2")
        self.verticalLayout.addWidget(self.Area_EastChinaSea_Cbox_2)
        self.verticalLayout_11.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_12.addLayout(self.horizontalLayout)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.theSeasPage_temp_EditLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.theSeasPage_temp_EditLine.setObjectName("theSeasPage_temp_EditLine")
        self.verticalLayout_2.addWidget(self.theSeasPage_temp_EditLine)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.theSeasPage_Sal_EditLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.theSeasPage_Sal_EditLine.setObjectName("theSeasPage_Sal_EditLine")
        self.verticalLayout_3.addWidget(self.theSeasPage_Sal_EditLine)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.theSeasPage_DisOxy_EditLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.theSeasPage_DisOxy_EditLine.setObjectName("theSeasPage_DisOxy_EditLine")
        self.verticalLayout_4.addWidget(self.theSeasPage_DisOxy_EditLine)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18)
        self.theSeasPage_Phos_EditLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.theSeasPage_Phos_EditLine.setObjectName("theSeasPage_Phos_EditLine")
        self.verticalLayout_5.addWidget(self.theSeasPage_Phos_EditLine)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_8.addWidget(self.label_16)
        self.theSeasPage_Nitrous_EditLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.theSeasPage_Nitrous_EditLine.setObjectName("theSeasPage_Nitrous_EditLine")
        self.verticalLayout_8.addWidget(self.theSeasPage_Nitrous_EditLine)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.theSeasPage_Nitric_EditLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.theSeasPage_Nitric_EditLine.setObjectName("theSeasPage_Nitric_EditLine")
        self.verticalLayout_7.addWidget(self.theSeasPage_Nitric_EditLine)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_5)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_6.addWidget(self.label_17)
        self.theSeasPage_Sas_EditLine = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_5)
        self.theSeasPage_Sas_EditLine.setObjectName("theSeasPage_Sas_EditLine")
        self.verticalLayout_6.addWidget(self.theSeasPage_Sas_EditLine)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.Page2Button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        self.Page2Button.setFocusPolicy(QtCore.Qt.TabFocus)
        self.Page2Button.setObjectName("Page2Button")
        self.horizontalLayout_4.addWidget(self.Page2Button)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.gridLayout_5.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.Calendar_textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        self.Calendar_textEdit.setEnabled(False)
        self.Calendar_textEdit.setObjectName("Calendar_textEdit")
        self.gridLayout_5.addWidget(self.Calendar_textEdit, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_6.addWidget(self.scrollArea_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_6.sizePolicy().hasHeightForWidth())
        self.scrollArea_6.setSizePolicy(sizePolicy)
        self.scrollArea_6.setMinimumSize(QtCore.QSize(600, 521))
        self.scrollArea_6.setMaximumSize(QtCore.QSize(554, 521))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 598, 519))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_6)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_26.setObjectName("label_26")
        self.gridLayout_16.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_20.setObjectName("label_20")
        self.gridLayout_16.addWidget(self.label_20, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_23.setObjectName("label_23")
        self.gridLayout_16.addWidget(self.label_23, 0, 2, 1, 1)
        self.PredictPage_3ea_pridet_Button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        self.PredictPage_3ea_pridet_Button.setObjectName("PredictPage_3ea_pridet_Button")
        self.gridLayout_16.addWidget(self.PredictPage_3ea_pridet_Button, 0, 3, 2, 1)
        self.PredictPage_3ea_Temp_Edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_3ea_Temp_Edit.setObjectName("PredictPage_3ea_Temp_Edit")
        self.gridLayout_16.addWidget(self.PredictPage_3ea_Temp_Edit, 1, 0, 1, 1)
        self.PredictPage_3ea_Sal_Edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_3ea_Sal_Edit.setObjectName("PredictPage_3ea_Sal_Edit")
        self.gridLayout_16.addWidget(self.PredictPage_3ea_Sal_Edit, 1, 1, 1, 1)
        self.PredictPage_3ea_DisOxy_Edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_3ea_DisOxy_Edit.setObjectName("PredictPage_3ea_DisOxy_Edit")
        self.gridLayout_16.addWidget(self.PredictPage_3ea_DisOxy_Edit, 1, 2, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.PredictPage_3ea_textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_3ea_textEdit.setObjectName("PredictPage_3ea_textEdit")
        self.gridLayout_17.addWidget(self.PredictPage_3ea_textEdit, 1, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_21.setObjectName("label_21")
        self.gridLayout_18.addWidget(self.label_21, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_24.setObjectName("label_24")
        self.gridLayout_18.addWidget(self.label_24, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_22.setObjectName("label_22")
        self.gridLayout_18.addWidget(self.label_22, 0, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_25.setObjectName("label_25")
        self.gridLayout_18.addWidget(self.label_25, 0, 3, 1, 1)
        self.PredictPage_4ea_pridet_Button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        self.PredictPage_4ea_pridet_Button.setObjectName("PredictPage_4ea_pridet_Button")
        self.gridLayout_18.addWidget(self.PredictPage_4ea_pridet_Button, 0, 4, 2, 1)
        self.PredictPage_4ea_Phos_Edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_4ea_Phos_Edit.setObjectName("PredictPage_4ea_Phos_Edit")
        self.gridLayout_18.addWidget(self.PredictPage_4ea_Phos_Edit, 1, 0, 1, 1)
        self.PredictPage_4ea_Nitrous_Edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_4ea_Nitrous_Edit.setObjectName("PredictPage_4ea_Nitrous_Edit")
        self.gridLayout_18.addWidget(self.PredictPage_4ea_Nitrous_Edit, 1, 1, 1, 1)
        self.PredictPage_4ea_Nitric_Edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_4ea_Nitric_Edit.setObjectName("PredictPage_4ea_Nitric_Edit")
        self.gridLayout_18.addWidget(self.PredictPage_4ea_Nitric_Edit, 1, 2, 1, 1)
        self.PredictPage_4ea_Sas_Edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_4ea_Sas_Edit.setObjectName("PredictPage_4ea_Sas_Edit")
        self.gridLayout_18.addWidget(self.PredictPage_4ea_Sas_Edit, 1, 3, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.PredictPage_4ea_textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_4ea_textEdit.setObjectName("PredictPage_4ea_textEdit")
        self.gridLayout_19.addWidget(self.PredictPage_4ea_textEdit, 1, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_19, 1, 0, 1, 1)
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.PredictPage_7ea_Phos_Edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_7ea_Phos_Edit.setObjectName("PredictPage_7ea_Phos_Edit")
        self.gridLayout_20.addWidget(self.PredictPage_7ea_Phos_Edit, 3, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_54.setObjectName("label_54")
        self.gridLayout_20.addWidget(self.label_54, 0, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_53.setObjectName("label_53")
        self.gridLayout_20.addWidget(self.label_53, 0, 1, 1, 1)
        self.PredictPage_7ea_Sal_Edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_7ea_Sal_Edit.setObjectName("PredictPage_7ea_Sal_Edit")
        self.gridLayout_20.addWidget(self.PredictPage_7ea_Sal_Edit, 1, 1, 1, 1)
        self.PredictPage_7ea_DisOxy_Edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_7ea_DisOxy_Edit.setObjectName("PredictPage_7ea_DisOxy_Edit")
        self.gridLayout_20.addWidget(self.PredictPage_7ea_DisOxy_Edit, 1, 2, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_59.setObjectName("label_59")
        self.gridLayout_20.addWidget(self.label_59, 2, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_55.setObjectName("label_55")
        self.gridLayout_20.addWidget(self.label_55, 0, 2, 1, 1)
        self.PredictPage_7ea_pridet_Button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        self.PredictPage_7ea_pridet_Button.setObjectName("PredictPage_7ea_pridet_Button")
        self.gridLayout_20.addWidget(self.PredictPage_7ea_pridet_Button, 0, 3, 2, 1)
        self.PredictPage_7ea_Temp_Edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_7ea_Temp_Edit.setObjectName("PredictPage_7ea_Temp_Edit")
        self.gridLayout_20.addWidget(self.PredictPage_7ea_Temp_Edit, 1, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_57.setObjectName("label_57")
        self.gridLayout_20.addWidget(self.label_57, 2, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_56.setObjectName("label_56")
        self.gridLayout_20.addWidget(self.label_56, 2, 2, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents_6)
        self.label_58.setObjectName("label_58")
        self.gridLayout_20.addWidget(self.label_58, 2, 3, 1, 1)
        self.PredictPage_7ea_Nitric_Edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_7ea_Nitric_Edit.setObjectName("PredictPage_7ea_Nitric_Edit")
        self.gridLayout_20.addWidget(self.PredictPage_7ea_Nitric_Edit, 3, 2, 1, 1)
        self.PredictPage_7ea_Sas_Edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_7ea_Sas_Edit.setObjectName("PredictPage_7ea_Sas_Edit")
        self.gridLayout_20.addWidget(self.PredictPage_7ea_Sas_Edit, 3, 3, 1, 1)
        self.PredictPage_7ea_Nitrous_Edit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_7ea_Nitrous_Edit.setObjectName("PredictPage_7ea_Nitrous_Edit")
        self.gridLayout_20.addWidget(self.PredictPage_7ea_Nitrous_Edit, 3, 1, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_20, 0, 0, 1, 1)
        self.PredictPage_7ea_textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_6)
        self.PredictPage_7ea_textEdit.setObjectName("PredictPage_7ea_textEdit")
        self.gridLayout_21.addWidget(self.PredictPage_7ea_textEdit, 1, 0, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_21, 2, 0, 1, 1)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout_23.addWidget(self.scrollArea_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(600, 519))
        self.label_2.setMaximumSize(QtCore.QSize(554, 519))
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "염분"))
        self.label_6.setText(_translate("Dialog", "용존산소"))
        self.label_9.setText(_translate("Dialog", "인산염인"))
        self.label_10.setText(_translate("Dialog", "질산규소"))
        self.label_12.setText(_translate("Dialog", "규산규소"))
        self.label_4.setText(_translate("Dialog", "수온"))
        self.label_11.setText(_translate("Dialog", "아질산질소"))
        self.All_Data_read_csv_Pushbutton.setText(_translate("Dialog", "출력하기"))
        self.LoadFile_PushButton.setText(_translate("Dialog", "불러오기"))
        self.label.setText(_translate("Dialog", "csv파일을 입력하시오."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "All_Data"))
        self.label_27.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_27.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">&lt;해역을 선택하여 주세요&gt;</span></p></body></html>"))
        self.Area_EestSea_Cbox_2.setText(_translate("Dialog", "동해"))
        self.Area_WestSea_Cbox_2.setText(_translate("Dialog", "서해"))
        self.Area_SouthSea_Cbox_2.setText(_translate("Dialog", "남해"))
        self.Area_EastChinaSea_Cbox_2.setText(_translate("Dialog", "동중국해"))
        self.label_3.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">&lt; 해달 날짜의 평균 요소 값 &gt;</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "수온"))
        self.label_13.setText(_translate("Dialog", "염분"))
        self.label_14.setText(_translate("Dialog", "용존산소"))
        self.label_18.setText(_translate("Dialog", "인산염인"))
        self.label_16.setText(_translate("Dialog", "아질산질소"))
        self.label_15.setText(_translate("Dialog", "질산질소"))
        self.label_17.setText(_translate("Dialog", "규산규소"))
        self.Page2Button.setText(_translate("Dialog", "          버튼         "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Calender"))
        self.label_26.setText(_translate("Dialog", "수온"))
        self.label_20.setText(_translate("Dialog", "염분"))
        self.label_23.setText(_translate("Dialog", "용존산소"))
        self.PredictPage_3ea_pridet_Button.setText(_translate("Dialog", "3EA"))
        self.label_21.setText(_translate("Dialog", "인산염인"))
        self.label_24.setText(_translate("Dialog", "아질산질소"))
        self.label_22.setText(_translate("Dialog", "질산질소"))
        self.label_25.setText(_translate("Dialog", "규산규소"))
        self.PredictPage_4ea_pridet_Button.setText(_translate("Dialog", "4EA"))
        self.label_54.setText(_translate("Dialog", "수온"))
        self.label_53.setText(_translate("Dialog", "염분"))
        self.label_59.setText(_translate("Dialog", "인산염인"))
        self.label_55.setText(_translate("Dialog", "용존산소"))
        self.PredictPage_7ea_pridet_Button.setText(_translate("Dialog", "7EA"))
        self.label_57.setText(_translate("Dialog", "아질산질소"))
        self.label_56.setText(_translate("Dialog", "질산질소"))
        self.label_58.setText(_translate("Dialog", "규산규소"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Predict"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'휴먼명조\'; font-size:14pt;\">정선해양관측자료를 통해본 유해적조</span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">김준한 · 강민석 · 이동현 </span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">신라대학교 빅데이터연구실</span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\'; font-size:11pt;\">The toxic red tide, ocean observation information through the Choice</span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">Kim-Jun Han · Gang-Min Seok · Lee-Dong Hyeon</span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">Korea Silla Univercity BigData Lab</span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">E-mail : axzswq@sillain.ac.kr</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">적조현상은 우리의 생태계나 인류에게 위협적인 환경문제 중 하나이다. </span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">그 중에서 유해적조는 정말로 치명적이다. 이러한 적조 원인은 플랑크톤의 이상 증식이다. </span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">이상 증식에 대해서 연구는 많이 있지만, 정확히 어떤 성분이 어느 정도의 </span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">원인을 제공하는지 자세히 나온 자료가 없다.</span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">본 논문에서 저자들은 해양요인들 중 정선해양관측정보에서 </span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">수온, 염분, 용존산소, 인산염인, 아질산질소, 질산규소, 규산수소의 7개의 요소를 </span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">python의 pandas 라이브러리를 이용하여서 데이터 추출, 과거적조발생자료를 </span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">국립수산과학원에서 웹 크롤링한 후에 자료들과 통합하여서 </span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">영향력을 제공하는 요소를 로지스틱 회귀분석 방식으로 분석했다. </span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">2000~2017년 정보들을 대상으로 진행하였다.</span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">본 논문을 통해 해양에 적조가 생기는 이유를 정밀하게 발견하고 </span></p><p align=\"center\"><span style=\" font-family:\'휴먼명조\';\">적조발생을 예방하며 생태계와 학술계에 도움이 되기를 희망합니다.</span></p><p align=\"center\"><br/></p><p align=\"center\">담당 교수)윤홍원 교수님</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Epilogue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
